name: Build

on:
  push:
    branches:
    tags: [ '*' ]
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Maven
        run: mkdir ~/.m2 && cp .github/settings.xml ~/.m2/settings.xml

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -Dtest=\!SecureClientTest

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JARs
          path: target/*.jar

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        run: mvn --batch-mode -DskipTests deploy
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}

      - name: Trigger downstream builds
        if: startsWith(github.ref, 'refs/tags/')
        run: .github/trigger_deps.sh
        env:
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Notify slack
        if: github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: vlingo-ci
          SLACK_USERNAME: Bob the Builder
          SLACK_ICON: 'https://vlingo.io/wp-content/uploads/cropped-vlingo-favicon-180x180.png'
          SLACK_FOOTER: ''

      - name: Cleanup
        run: rm -rf ~/.m2/repository/io/vlingo
